apiVersion: v1
kind: ConfigMap
metadata:
  name: learnhub-config
  labels:
    app.kubernetes.io/name: learnhub-config
    app.kubernetes.io/part-of: learnhub
    app.kubernetes.io/component: config
data:
  APP_VERSION: "0.3.0"
  PORT: "8080"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_HEALTH_REQUESTS: "false"
  DEPLOYMENT_ENV: "kubernetes"
  JWT_ISSUER: "learnhub-capstone"
  POSTGRES_PORT: "5432"
  REDIS_ADDR: "redis:6379"
  NATS_URL: "nats://nats:4222"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "learnhub-content"
  SMTP_HOST: "smtp.local"
  USER_SERVICE_URL: "http://user-service"
  COURSE_SERVICE_URL: "http://course-service"
  ENROLLMENT_SERVICE_URL: "http://enrollment-service"
  PAYMENT_SERVICE_URL: "http://payment-service"
  NOTIFICATION_SERVICE_URL: "http://notification-service"
