apiVersion: v1
kind: ResourceQuota
metadata:
  name: learnhub-capstone-quota
  labels:
    app.kubernetes.io/name: learnhub-capstone-quota
    app.kubernetes.io/part-of: learnhub
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "60"
    services: "30"
    persistentvolumeclaims: "12"
    requests.storage: 10Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: learnhub-container-defaults
  labels:
    app.kubernetes.io/name: learnhub-container-defaults
    app.kubernetes.io/part-of: learnhub
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 5m
        memory: 16Mi
      max:
        cpu: "1"
        memory: 1Gi
