apiVersion: v2
name: payment-service
description: Helm chart for the LearnHub payment-service
type: application
version: 0.4.0
appVersion: "0.3.0"
dependencies:
  - name: learnhub-common
    version: 0.4.0
    repository: file://../learnhub-common
