apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learnhub-capstone-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: replicas-prod.yaml
  - path: images-prod.yaml
  - path: ingress-prod.yaml

