apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learnhub-capstone-dev
resources:
  - namespace.yaml
  - ../../base
  - ingress-localhost.yaml
patches:
  - path: replicas-dev.yaml
