apiVersion: v1
kind: Pod
metadata:
  name: triage-client
  namespace: triage-lab
  labels:
    app: learnhub-triage-client
    lab: "5.3"
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:8.10.1
      imagePullPolicy: IfNotPresent
      command:
        - curl
      args:
        - --fail
        - --silent
        - --show-error
        - --connect-timeout
        - "5"
        - --max-time
        - "8"
        - http://learnhub-triage-api/api/courses
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
