apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: learnhub-course-scale
  namespace: scale-lab
  labels:
    app: learnhub-course-scale
    component: course
    lab: "2.3"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: learnhub-course-scale
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
