replicaCount: 2

image:
  repository: learnhub/course-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  automount: false

service:
  type: ClusterIP
  port: 80

containerPort: 8080
serviceName: course-service-helm
appVersion: "0.1.0"

existingConfigMap: learnhub-config
existingSecret: learnhub-secret

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  cpuAverageUtilization: 50

