apiVersion: v1
kind: Service
metadata:
  name: {{ include "learnhub-course.fullname" . }}
  labels:
    {{- include "learnhub-course.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "learnhub-course.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

