replicaCount: 2

image:
  repository: learnhub/course-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080
serviceName: course-service-helm
appVersion: "0.1.0"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
